name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Build spect wheel
        run: |
          rm -rf ./dist/ ./build/ ./.eggs/ ./src/spect.egg-info/
          python3 ./setup.py bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.github_spect_release }}
          packages_dir: ./dist/
